name: Update files in forks

on:
  push:
    branches:
      - try-multi-gitter
  workflow_dispatch:

jobs: 
  update-forks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4
        
      - name: Install multi-gitter
        run: |
          curl -s https://raw.githubusercontent.com/lindell/multi-gitter/master/install.sh | sh

      - name: Update repositories
        env:
          GITHUB_TOKEN: ${{ secrets.MULTI_GITTER_TOKEN }}
        run: |
          multi-gitter run "$GITHUB_WORKSPACE/.github/scripts/update_files.sh" \
            -R TaniaGithub0401/actinia-core \
            --base-branch test-email-notification \
            -m "Test updating existing workflow with multi-gitter" \
            -B test-multi-gitter-workflow-update  \
            --author-name "TaniaGithub0401" \
            --author-email "tania_93xime@hotmail.com" \
            --log-level=debug
